# Generated by Django 4.2.24 on 2025-09-10 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('open_hours', '0006_activity_activity_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caravan_number', models.CharField(max_length=6, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('number_of_people', models.PositiveIntegerField()),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('attended', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_hours.session')),
            ],
            options={
                'verbose_name_plural': 'bookings',
            },
        ),
    ]
