# Generated by Django 4.2.24 on 2025-09-07 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_hours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='open_hours.activity'),
        ),
    ]
