# Generated by Django 4.2.24 on 2025-09-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_hours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('day_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=10)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='OpeningHours',
        ),
    ]
