# Generated by Django 4.2.24 on 2025-09-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_hours', '0002_openinghour_delete_openinghours'),
    ]

    operations = [
        migrations.CreateModel(
            name='activities',
            fields=[
                ('activity_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('max_number', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duration', models.DurationField()),
            ],
        ),
    ]
