# Generated by Django 4.2.24 on 2025-09-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_hours', '0004_remove_timetablesession_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.CharField(choices=[('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00')], max_length=5),
        ),
    ]
