# Generated by Django 4.2.24 on 2025-09-10 11:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_hours', '0005_alter_session_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
