# Generated by Django 4.2.24 on 2025-09-10 11:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_hours', '0006_activity_activity_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
