# Generated by Django 4.2.24 on 2025-09-12 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_hours', '0007_alter_activity_activity_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='booked_number',
        ),
    ]
