# Generated by Django 4.2.24 on 2025-09-13 15:36

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_hours', '0008_remove_session_booked_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openinghour',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='openinghour',
            name='open_time',
        ),
        migrations.AddField(
            model_name='openinghour',
            name='close',
            field=models.CharField(choices=[('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00')], default='17:00', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openinghour',
            name='open',
            field=models.CharField(choices=[('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00')], default='17:00', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
